### ISSUE TITLE
Why is the layouts folder empty?

### ISSUE THREAD

**Issue by bwc69151** [razonyang/hugo-theme-bootstrap-skeleton#29]
No files in there to match the demo

**Comment by razonyang** [comment]
Hi, I didn't get it, could you please explain it in detail?

**Comment by razonyang** [comment]
Hmm, how do you install this theme?
There is a file inside the [layouts](https://github.com/razonyang/hugo-theme-bootstrap-skeleton/tree/main/layouts), I don't understand what does the _empty_ mean.

**Comment by bwc69151** [comment]
Someone asked [this question](https://discourse.gohugo.io/t/sidebar-with-tabs-that-show-recent-and-featured-posts/44146) and I visited this repo to see the theme. But in the layouts folder, you don't have any files except the sidebar end one.

**Comment by razonyang** [comment]
Thanks for the details, this repo is a template of the [theme](https://github.com/razonyang/hugo-theme-bootstrap), that's why there aren't files in the `layouts` folder.

Btw, if I understand correctly, the question is about switching from [HBS ](https://github.com/razonyang/hugo-theme-bootstrap) theme to others, and how to add the sidebar with recent posts and featured posts on the new theme.
